title: 'Esterházy Móricz Általános Iskola'
default_lang: hu
author:
  name: 'Istvan Vig'
  email: istvan.vig@parphis.hu
taxonomies:
  - category
  - tag
metadata:
  description: 'esterházy móricz általános iskola'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
