enabled: true
navcolor: 'blue darken-3'
barcolor: 'blue darken-2'
acccolor: 'blue accent-1'
footcolor: 'grey darken-2'
footcolortext: white-text
dropdown:
  enabled: true
social:
  enabled: true
navimg:
  enabled: true
sideinfo:
  enabled: false
